name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Test
        run: |
          hostname
          whoami
          node -v
          dotnet --version